# .github/workflows/deploy-gameserver.yml
name: Deploy Game Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch SFTP credentials
      id: get-credentials
      run: |
        # Fetch user email
        USER_EMAIL=$(curl -s -X GET \
          "https://manage.hebergtonserv.com/api/client/auth/@me" \
          -H "Authorization: Bearer ${{ secrets.CLIENT_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.wisp.v1+json" | \
          jq -r '.attributes.email')
          
        SFTP_USERNAME="${USER_EMAIL}.${{ vars.SERVER_ID }}"
        echo "sftp_username=$SFTP_USERNAME" >> $GITHUB_OUTPUT
    
    - name: Sync to SFTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SFTP_HOST }}
        port: 2022
        username: ${{ steps.get-credentials.outputs.sftp_username }}
        password: ${{ secrets.USER_PASSWORD }}
        local_path: './*'
        remote_path: ${{ vars.SFTP_REMOTE_PATH }}
        sftp_only: true
        delete_remote_files: true
    
    - name: Wait for file sync completion
      run: sleep 10
    
    - name: Restart gameserver via WISP API
      run: |
        curl -X POST \
          "https://manage.hebergtonserv.com/api/client/servers/${{ vars.SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.CLIENT_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.wisp.v1+json" \
          -d '{"signal": "restart"}'
