# .github/workflows/deploy-gameserver.yml
name: Deploy Game Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch SFTP credentials from WISP API
      id: get-credentials
      run: |
        # Fetch user email from WISP Client API
        USER_EMAIL=$(curl -s -X GET \
          "https://manage.hebergtonserv.com/api/client/auth/@me" \
          -H "Authorization: Bearer ${{ secrets.CLIENT_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" | \
          jq -r '.attributes.email')
        
        echo "sftp_username=$USER_EMAIL" >> $GITHUB_OUTPUT
    
    - name: Sync to SFTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SFTP_HOST }}
        port: 2022
        username: ${{ steps.get-credentials.outputs.sftp_username }}
        password: ${{ secrets.USER_PASSWORD }}
        local_path: './*'
        remote_path: ${{ vars.SFTP_REMOTE_PATH }}
        sftp_only: true
        delete_remote_files: true
    
    - name: Wait for file sync completion
      run: sleep 10
    
    - name: Restart gameserver via WISP API
      run: |
        # Get server power status first
        POWER_STATUS=$(curl -s -X GET \
          "https://manage.hebergtonserv.com/api/client/servers/${{ vars.SERVER_ID }}/resources" \
          -H "Authorization: Bearer ${{ secrets.WISP_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" | \
          jq -r '.attributes.current_state')
        
        echo "Current server state: $POWER_STATUS"
        
        # Stop the server if it's running
        if [ "$POWER_STATUS" = "running" ]; then
          echo "Stopping server..."
          curl -X POST \
            "https://manage.hebergtonserv.com/api/client/servers/${{ vars.SERVER_ID }}/power" \
            -H "Authorization: Bearer ${{ secrets.WISP_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Accept: Application/vnd.pterodactyl.v1+json" \
            -d '{"signal": "stop"}'
          
          # Wait for server to stop
          echo "Waiting for server to stop..."
          sleep 30
        fi
        
        # Start the server
        echo "Starting server..."
        curl -X POST \
          "https://manage.hebergtonserv.com/api/client/servers/${{ vars.SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.WISP_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" \
          -d '{"signal": "start"}'
        
        echo "Server restart initiated successfully"
